linters:
  disable-all: true
  enable:
    - gci
    - gofumpt
    - gosimple
    - govet
    - ineffassign
    - misspell
    - staticcheck
    - unconvert
    - unused
    - usestdlibvars

linters-settings:
  gci:
    custom-order: true
    sections:
      - standard
      - default
      - prefix(github.com/xjasonlyu/tun2socks)
  staticcheck:
    go: '1.22'
