linters:
  disable-all: true
  enable:
    - gofumpt
    - staticcheck
    - govet
    - gci

linters-settings:
  gci:
    sections:
      - standard
      - prefix(github.com/xjasonlyu/tun2socks)
      - default
  staticcheck:
    go: '1.18'
